### ISSUE TITLE
Seems Like there are some differences between GitHub code and running code

### ISSUE THREAD

**Issue by wse320** [trusttoken/trueUSD#17]
I download the code on the etherscan and compared it to the Github code, there are a lot of differences.
Besides, I can't deploy it on the rinkeby or the Ganache, the TrueUSD.sol always meet the problem "out of gas". But the code is not that long. Anyone can tell me what's wrong with it?

**Comment by zachlysobey** [comment]
The deployed code will be different than the source b/c of import resolution (and perhaps other things?)

*somewhat related: #32*

**Comment by wjmelements** [comment]
The flattened code on etherscan is correct and compiles to the bytecode on-chain. See #32.
