### ISSUE TITLE
creating trueusd token 

### ISSUE THREAD

**Issue by anubnair** [trusttoken/trueUSD#67]
I have seen contract -> 0x0000000000085d4780B73119b644AE5ecd22b376 in etherscan, the same is available in rinkeby/ropsten? I am trying to create trueusd token . I am new to smart contract. Can anyone help me with this? I have gone through the deployed contract and couldn't find a way.

**Comment by wjmelements** [comment]
What do you mean when you say you are trying to create TrueUSD?

You can purchase TrueUSD on https://app.trusttoken.com

**Comment by anubnair** [comment]
I haven't purchased with app.trusttoken. I am trying to build an app, where I can purchase trueusd with my eth token(doing with rinkeby/ropsten test accounts now). Metamask is able to add any contract which is published in rinkeby/ropsten, and I was able to add TrueUSD to my account via metamask. For main Etherium network they use the latest released contract (Contract address - 0x0000000000085d4780B73119b644AE5ecd22b376) for creating token. (means they didn't published a trueusd token and they are using this existing contract for creating token)
I need to know few things:
1) This contract is deployed in main Etherium network, is it deployed in testnet? if so, can you share the contract address?
2) How to generate a token for the given etherium address. (I can generate an eth address via web3 ), but how to generate a token for the given address
3) MultisigOwner.sol is for multisigning right?Any examples available how to use this?

**Comment by wjmelements** [comment]
The easiest way to deploy contracts on the testnets is with https://remix.ethereum.org

We have several testnet deployments but they are not kept up to date.
@terryli0095 can send you some testnet TUSD if you provide an address.

The multisig owner contract is not currently in use.

**Comment by anubnair** [comment]
@wjmelements Thanks for the reply. 0x0E9f2c5B7B64639f9b894159D4E39E5f8A19EeAd
It will be great if you can help me a way to load TUSD so that I can

**Comment by anubnair** [comment]
@wjmelements @terryli0095 Can you send some testnet TUSD to 0x0E9f2c5B7B64639f9b894159D4E39E5f8A19EeAd ?

**Comment by anubnair** [comment]
I have gone through contract and couldn't figure out how to deposit token with my eth balance. It will be great if you guys can help me! If it is already there in test, it will be great to point me to the right file. I need some testnet TUSD.

**Comment by wjmelements** [comment]
@terryli0095

**Comment by terryli0095** [comment]
Sent it to you @anubnair

https://rinkeby.etherscan.io/tx/0x48c6734d70dc6b8fbe4e050b8280eb9d0a77da83068985803079c2a25ee0cee1

https://rinkeby.etherscan.io/tx/0xe09d46d88cfb879107366948b0a9bd05c4b259c59c1b05c7fa535d537d830742

**Comment by terryli0095** [comment]
Just realized the version you are using is slightly outdated. I will deploy a brand new version of the contract and send it to you so that the gas limit is correct for you. Please check back on after the weekend
@anubnair

**Comment by anubnair** [comment]
Ok. Can you please let me know the transaction details? Or new contract address?

**Comment by umanggoyal89** [comment]
@terryli0095 is it possible to get some TUSD on Ropsten Testnet, as i am creating a Smart Contract for ERC-20 coins and need to make it compatible with TUSD as well, so wondering if you can share some tusd on my below address please.
my ETH address is: 0xf17f52151EbEF6C7334FAD080c5704D77216b732

Thanks for all your help :)

**Comment by wjmelements** [comment]
We do not have a Ropsten deployment.

If you support any ERC20 token you will support TrueUSD. If you are not using any TrueCurrency-specific features such as Autosweep, the recipient callback, or redemption, it is not important for you to actually use TrueUSD.

If you must test with our contracts on Ropsten, you can attempt to deploy them yourself using Remix. The minimal steps are:

1. Deploy OwnedUpgradeabilityProxy
2. Deploy [TrueUSDMock](https://github.com/trusttoken/true-currencies/blob/master/contracts/mocks/TrueUSDMock.sol)
3. OwnedUpgradeabilityProxy.upgradeTo(TokenMock.address)
4. TokenMock(OwnedUpgradeabilityProxy.address).initialize()
5. Deploy TrueUSD
6. OwnedUpgradeabilityProxy.upgradeTo(TrueUSD.address)
7. TrueUSD(OwnedUpgradabilityProxy.address).mint(to, value)
