### ISSUE TITLE
do you hava contract in the rinkeby network

### ISSUE THREAD

**Issue by bingge1** [trusttoken/trueUSD#73]
do you hava contract in the rinkeby network ,if  your has deployed ,show me the contract address,thanks!

**Comment by wjmelements** [comment]
https://rinkeby.etherscan.io/address/0x1331f1a00336390ced0d5c74543738a33c8ed370

**Comment by terryli0095** [comment]
@bingge1  deploying a new official one very soon that will be maintained. Please check back later

**Comment by wjmelements** [comment]
Rinkeby Contracts:
[TrueUSD](https://rinkeby.etherscan.io/address/0x0000000000085d4780b73119b644ae5ecd22b376)
[TUSD Faucet](https://rinkeby.etherscan.io/address/0x0000000000075efbee23fe2de1bd0b7690883cc9)
[Registry](https://rinkeby.etherscan.io/address/0x0000000000013949f288172bd7e36837bddc7211)

To obtain some test TrueUSD, use the `faucet` function of the Faucet contract.

**Comment by bingge1** [comment]
ok, Thanks!
