### ISSUE TITLE
Deploy own copy of trueUSD token in rinkeby

### ISSUE THREAD

**Issue by du2zy** [trusttoken/trueUSD#75]
Hello!

I find a way to create my own copy of trueUSD token in rinkeby testnet. I was deploy trueUSD token, but I can't initialize it.

Can you write steps to create and initialize my own copy of trueUSD?

**Comment by terryli0095** [comment]
I'll write up a deployment guide this weekend. Check back on Monday!

**Comment by wjmelements** [comment]
If you don't want to wait until then, the steps are verbatim the steps laid out in the beforeEach of https://github.com/trusttoken/trueUSD/blob/master/test/GasProfile.test.js

**Comment by terryli0095** [comment]
Having trouble with truffle, will be delayed

**Comment by du2zy** [comment]
I tried the command `truffle deploy --network rinkeby`. It works fine, but useless, because `migrations/2_deploy_contracts.js` is empty.
@wjmelements how i can execute commands from `GasProfiel.test.js`? I tried to copy it in `truffle deploy --network rinkeby`, but error is occured: `ReferenceError: artifacts is not defined`.

**Comment by du2zy** [comment]
@terryli0095 Can you send some tokens for testing in rinkeby, please: `0x01d7f61f4d636205b1077bb496c4238a6b994288`
Sorry for offtop. May be it is good idea to create different topic for such requests?

**Comment by wjmelements** [comment]
Rinkeby Contracts:
[TrueUSD](https://rinkeby.etherscan.io/address/0x0000000000085d4780b73119b644ae5ecd22b376)
[TUSD Faucet](https://rinkeby.etherscan.io/address/0x0000000000075efbee23fe2de1bd0b7690883cc9)
[Registry](https://rinkeby.etherscan.io/address/0x0000000000013949f288172bd7e36837bddc7211)

To obtain some test TrueUSD, use the `faucet` function of the Faucet contract.
